"""
Shield Technology Domain Enums.
Strictly typed business domain definitions for Security & IT Operations.
"""

from enum import Enum


class EventType(str, Enum):
    CTA_CLICK = "CTA_CLICK"
    PAGE_VIEW = "PAGE_VIEW"
    TIME_SPENT = "TIME_SPENT"
    FUNNEL_STEP = "FUNNEL_STEP"
    FORM_START = "FORM_START"
    QUOTE_SUBMIT = "QUOTE_SUBMIT"
    DOWNLOAD_SPECS = "DOWNLOAD_SPECS"


class LeadDomain(str, Enum):
    VIDEOSURVEILLANCE = "VIDEOSURVEILLANCE"
    ALARM_INTRUSION = "ALARM_INTRUSION"
    FIRE_DETECTION = "FIRE_DETECTION"
    ACCESS_CONTROL = "ACCESS_CONTROL"
    IT_INFRASTRUCTURE = "IT_INFRASTRUCTURE"
    SLA_MAINTENANCE = "SLA_MAINTENANCE"


class ClientType(str, Enum):
    ENTERPRISE = "ENTERPRISE"
    INDUSTRY = "INDUSTRY"
    GOVERNMENT = "GOVERNMENT"
    OIV = "OIV"  # Operateur d'Importance Vitale
    RESIDENTIAL_VIP = "RESIDENTIAL_VIP"
    RETAIL = "RETAIL"


class ProjectUrgency(str, Enum):
    IMMEDIATE_MISSION_CRITICAL = "IMMEDIATE_MISSION_CRITICAL"
    URGENT_1_WEEK = "URGENT_1_WEEK"
    PLANNED_1_MONTH = "PLANNED_1_MONTH"
    EXPLORATORY_QUOTE = "EXPLORATORY_QUOTE"


class QualificationTier(str, Enum):
    TIER_1_ENTERPRISE_VIP = "TIER_1_ENTERPRISE_VIP"
    TIER_2_QUALIFIED = "TIER_2_QUALIFIED"
    TIER_3_STANDARD = "TIER_3_STANDARD"
    UNQUALIFIED_LOW_CONFIDENCE = "UNQUALIFIED_LOW_CONFIDENCE"


class EquipmentCategory(str, Enum):
    CAMERA_4K_IA = "CAMERA_4K_IA"
    ALARM_GRADE_3 = "ALARM_GRADE_3"
    ACCESS_BIOMETRIC = "ACCESS_BIOMETRIC"
    FIRE_EN54 = "FIRE_EN54"
    IT_NETWORKING = "IT_NETWORKING"
    SLA_SERVICE = "SLA_SERVICE"
